FROM golang:1.15.3 as builder
ENV BANK_GATEWAY=bank-gateway
ENV SHIPPING_GATEWAY=shipping-gateway
WORKDIR /module
COPY ./go.mod /module/go.mod
COPY ./go.sum /module/go.sum
RUN go mod download
COPY . /module
RUN go install -v ./...