

name: CI/CD Frontend Vue

on:
  push:
    branches:
    - master
    
jobs:
  install_libs:
    runs-on: self-hosted
    steps:
    - name: npm install
      run: make install_dependency_frontend_vue

  # analysis:
  #   runs-on: self-hosted
  #   steps:
  #   - name: code analysis
  #     run: make code_analysis_frontend_vue

  
  # unittest:
  #   runs-on: self-hosted
  #   steps:
  #   - name: unittest
  #     run: make run_unittest_frontend_vue
