

name: CI/CD Frontend Vue

on:
  push:
    branches:
    # - master
    - feature/cicd

env:
  DOC_HUB_USER: ${{ secrets.DOC_HUB_USER }}
  DOC_HUB_PASS: ${{ secrets.DOC_HUB_PASS }}

jobs:
  build_test:
    name: Build for Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build Image
      run: |-
        docker build -f ${PWD}/store-web-vue/Dockerfile.dev --tag tokdev/shopping-cart-1/store-web-vue:dev0.0.1 ${PWD}/store-web-vue
    - name: Install dependency
      run: |-
        docker run -v ${PWD}/store-web-vue:/usr/src/app -w /usr/src/app tokdev/shopping-cart-1/store-web-vue:dev0.0.1 npm install
    - uses: shrink/actions-docker-extract@v1
      with:
        image: tokdev/shopping-cart-1/store-web-vue:dev0.0.1
        path: /usr/src/app/.
    - name: Upload node_modules
      with:
        path: ${{ steps.extract.outputs.destination }}
        name: node_modules
        

  # analysis:
  #   runs-on: ubuntu-latest
  #   needs: build_tet
  #   steps:
  #   - name: Checkout
  #     uses: actions/checkout@v2
  #   - uses: actions/download-artifact@v2
  #     with:
  #       name: my-artifact
  #       path: ${PWD}/store-web-vue/node_modules
  #   - name: code analysis
  #     run: make code_analysis_frontend_vue

  
  # unittest:
  #   runs-on: ubuntu-latest
  #   needs: build_tet
  #   steps:
  #   - name: Checkout
  #     uses: actions/checkout@v2
  #   - uses: actions/download-artifact@v2
  #     with:
  #       name: my-artifact
  #       path: ${PWD}/store-web-vue/node_modules
  #   - name: unittest
  #     run: make run_unittest_frontend_vue
