

name: CI/CD Frontend Vue

on:
  push:
    branches:
    # - master
    - feature/cicd

env:
  DOC_HUB_USER: ${{ secrets.DOC_HUB_USER }}
  DOC_HUB_PASS: ${{ secrets.DOC_HUB_PASS }}

jobs:
  build_test:
    name: Build for Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.15.1]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm run lint
    - run: npm run test:unit
        

  # analysis:
  #   runs-on: ubuntu-latest
  #   needs: build_tet
  #   steps:
  #   - name: Checkout
  #     uses: actions/checkout@v2
  #   - uses: actions/download-artifact@v2
  #     with:
  #       name: my-artifact
  #       path: ${PWD}/store-web-vue/node_modules
  #   - name: code analysis
  #     run: make code_analysis_frontend_vue

  
  # unittest:
  #   runs-on: ubuntu-latest
  #   needs: build_tet
  #   steps:
  #   - name: Checkout
  #     uses: actions/checkout@v2
  #   - uses: actions/download-artifact@v2
  #     with:
  #       name: my-artifact
  #       path: ${PWD}/store-web-vue/node_modules
  #   - name: unittest
  #     run: make run_unittest_frontend_vue
