

name: CI/CD Frontend Vue

on:
  push:
    branches:
    # - master
    - feature/cicd

env:
  DOC_HUB_USER: ${{ secrets.DOC_HUB_USER }}
  DOC_HUB_PASS: ${{ secrets.DOC_HUB_PASS }}

jobs:
  build_tet:
    name: Build for Test
    runs-on: ubuntu-latest
    steps:
    -
      name: Build Push
      uses: whoan/docker-build-with-cache-action@v5
      with:
        username: $DOC_HUB_USER
        password: $DOC_HUB_PASS
        image_name: tokdev/shopping-cart-1/store-web-vue
        image_tag: dev0.0.1
        push_git_tag: true
        registry: docker.io
        context: store-web-vue
        dockerfile: Dockerfile.dev
        # build_extra_args: "--compress=true --build-arg=hello=world"
        # push_image_and_stages: docker build -f store-web-vue/Dockerfile.dev --tag tokdev/shopping-cart-1/store-web-vue:dev0.0.1 store-web-vue

        # tags: tokdev/shopping-cart-1/store-web-vue:dev0.0.1
        # cache-to: type=local,dest=/tmp/.buildx-cache
        # cache-from: type=local,dest=/tmp/.buildx-cache
        # cache-from: type=registry,ref=tokdev/shopping-cart-1/store-web-vue:dev0.0.1
        # cache-from: type=local,src=store-web-vue/node_modules
        # cache-to: type=local,dest=store-web-vue/node_modules
        

  # analysis:
  #   runs-on: ubuntu-latest
  #   needs: build_tet
  #   steps:
  #   - name: Checkout
  #     uses: actions/checkout@v2
  #   - uses: actions/download-artifact@v2
  #     with:
  #       name: my-artifact
  #       path: ${PWD}/store-web-vue/node_modules
  #   - name: code analysis
  #     run: make code_analysis_frontend_vue

  
  # unittest:
  #   runs-on: ubuntu-latest
  #   needs: build_tet
  #   steps:
  #   - name: Checkout
  #     uses: actions/checkout@v2
  #   - uses: actions/download-artifact@v2
  #     with:
  #       name: my-artifact
  #       path: ${PWD}/store-web-vue/node_modules
  #   - name: unittest
  #     run: make run_unittest_frontend_vue
