

name: CI/CD Frontend Vue

on:
  push:
    branches:
    # - master
    - feature/cicd

env:
  DOC_HUB_USER: ${{ secrets.DOC_HUB_USER }}
  DOC_HUB_PASS: ${{ secrets.DOC_HUB_PASS }}

jobs:
  build_test:
    name: Build for Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.15.1]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: cd store-web-vue && npm install
    - run: cd store-web-vue && npm run lint
    - run: cd store-web-vue && npm run test:unit
    - uses: actions/upload-artifact@v2
      with:
        name: my-artifact
        path: store-web-vue/node_modules
        

  analysis:
    needs: build_test
    runs-on: ubuntu-latest
    name: analysis testing
    strategy:
      matrix:
        node-version: [14.15.1]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/upload-artifact@v2
      with:
        name: my-artifact
        path: store-web-vue/node_modules
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: cd store-web-vue && npm run lint

  # unittest:
  #   needs: build_test
  #   runs-on: ubuntu-latest
  #   steps:
  #   - name: Checkout
  #     uses: actions/checkout@v2
  #   - uses: actions/download-artifact@v2
  #     with:
  #       name: my-artifact
  #       path: ${PWD}/store-web-vue/node_modules
  #   - name: unittest
  #     run: make run_unittest_frontend_vue
